on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/cache@v4
        with:
          path: build/_deps/*-src
          key: cmake-dependency-src-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-dependency-src-

      - uses: actions/cache@v4
        with:
          path: |
            build/_deps/*-build
            build/_deps/*-subbuild
          key: cmake-dependency-builds-${{ runner.os }}-benchmark-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-dependency-builds-${{ runner.os }}-benchmark-
            cmake-dependency-builds-${{ runner.os }}-

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          # release
          options: CMAKE_BUILD_TYPE=Release
          build-args: --config Release --target Benchmark

      - name: Run Benchmark
        run: |
          ./build/benchmark/Benchmark | tee build/benchmark-result.txt

      - uses: actions/upload-artifact@v4
        with:
          name: benchmark-result
          path: build/benchmark-result.txt

  benchmark-target:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          submodules: 'recursive'

      - uses: actions/cache@v4
        with:
          path: build/_deps/*-src
          key: cmake-dependency-src-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-dependency-src-

      - uses: actions/cache@v4
        with:
          path: |
            build/_deps/*-build
            build/_deps/*-subbuild
          key: cmake-dependency-builds-${{ runner.os }}-benchmark-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-dependency-builds-${{ runner.os }}-benchmark-
            cmake-dependency-builds-${{ runner.os }}-

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          # release
          options: CMAKE_BUILD_TYPE=Release
          build-args: --config Release --target Benchmark

      - name: Run Benchmark
        run: |
          ./build/benchmark/Benchmark | tee build/benchmark-result-target.txt

      - uses: actions/upload-artifact@v4
        with:
          name: benchmark-result-target
          path: build/benchmark-result-target.txt
