on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  ctest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/cache@v4
        with:
          path: build/_deps/*-src
          key: cmake-dependency-src-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-dependency-src-

      - uses: actions/cache@v4
        with:
          path: |
            build/_deps/*-build
            build/_deps/*-subbuild
          key: cmake-dependency-builds-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-dependency-builds-${{ runner.os }}-

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          args: -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: Debug

      - name: Check Coverage
        if: ${{ matrix.os != 'windows' }}
        uses: threeal/gcovr-action@xml-out
        with:
          xml-out: './build/coverage.xml'
          coveralls-out: './build/coveralls.json'
          excludes: |
            build/* 
            test/*

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          files: ./build/coverage.xml
          disable_search: true
